server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt

spring:
  cloud:
    consul:
      discovery:
        health-check-path: ${server.context-path}${management.context-path}/health
        tags: management.context-path=${server.context-path}${management.context-path}
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
