server:  
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always  
spring:
  # 配置zookeeper地址
  cloud:
    zookeeper:
      connect-string: localhost:2181
  boot:  
    admin:  
      notify:  
        mail:  
          enabled: true
          to: jijia128@163.com
          from: derek256@163.com
#          ignore-changes: UNKNOWN:UP
          ignore-changes:
            -
              "*:UP" #从任何状态到up状态都不要发邮件通知
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        #,unieap-eureka-server-single
        location: turbine
  mail:
    host: smtp.163.com
    username: derek256@163.com
    password: derek256
    properties:
        mail.smtp.auth : true
        mail.smtp.timeout : 2000
        mail.smtp.starttls.enable : true
        mail.smtp.starttls.required : true
  zipkin:
    base-url: http://127.0.0.1:11008    # zipkin监控地址

