server:
  port: 7768
  tomcat:
    uri-encoding: UTF-8
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always  
spring:
  application:
    name: eureka-client
  http:
    encoding:
      charset:  utf8
      force: true
      enabled: true
  zipkin:
    base-url: http://127.0.0.1:11008
  # 配置zookeeper地址
  cloud:
    zookeeper:
      connect-string: localhost:2181

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.neusoft: DEBUG     
    com.netflix: DEBUG                    #用于心跳检测输出的日志