server:
  port: 1111
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: tomcat
spring:
  zipkin:
    base-url: http://127.0.0.1:11008
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  # 配置zookeeper地址
  cloud:
    zookeeper:
      connect-string: localhost:2181

ribbon:
  ServerListRefreshInterval: 1000    
logging:
  level:
    root: INFO
    com.central: DEBUG  
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
turbine:
  app-config:  auth-gateway,admin-server,auth-server,eureka-server,user-center	               #需要监控的服务名
  aggregator:
    cluster-config: default   #需要监控的服务集群名
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix:
      default: actuator/hystrix.stream    #key是clusterConfig集群的名字，value是hystrix监控的后缀，springboot2.0为actuator/hystrix.stream #http://localhost:1111/turbine.stream